- pkg/controller/grouppermission/grouppermission_controller.go
clusterRoleList and clusterRoleBindingList are both not of object type and therefore we can't "create" them on the cluster
> fix clusterRoleList and clusterRoleBindingList

- build/Dockerfile
- standard.mk
This PR copies the Dockerfile and standard.mk changes from the managed-velero-operator to bring in the following changes:
- Use GOPROXY if set
- Cache go modules in a layer during build to improve build times
- Use go1.12 and UBI for base images
> Modify docker build to use GOPROXY if set

- pkg/controller/subjectpermission/subjectpermission_controller.go
add in fmt.Sprintf for simplicity and to keep lines shorter. These changes got left out of PR #20.
> Add fmt.Sprintf() for logging status conditions

- deploy/crds/managed_v1alpha1_subjectpermission_crd.yaml
- pkg/apis/managed/v1alpha1/subjectpermission_types.go
- pkg/controller/namespace/namespace_controller.go
- pkg/controller/subjectpermission/subjectpermission_controller.go
- pkg/controller/utils/controllerutil.go
Currently no conditions are being updated when ClusterRoleBindings and RoleBindings are being created. This PR adds the functionality to add/update conditions in the event of ClusterRoleBinding and/or RoleBinding creation.
> Add conditions functionality to SubjectPermission object

- deploy/cluster_role.yaml
- deploy/crds/managed_v1alpha1_subjectpermission_cr.yaml
- pkg/controller/namespace/namespace_controller.go
- pkg/controller/subjectpermission/subjectpermission_controller.go
- pkg/controller/utils/controllerutil.go
currently operator is broken when the clusterRoleName we pass in the CR does not exist on the cluster. The solution is "all-or-nothing". If any clusterRoleNames do not exist on the cluster, operator will update status and exit.
> Add check for clusterRoleNames

- deploy/cluster_role_binding.yaml
In order for the rbac operator to have correct permissions to assign to subjects, it's SA needs to be bound to the clusterrole `cluster-admin`
> Bind rbac ServiceAccount to cluster-admin

- deploy/prom-k8s-role.yaml
- deploy/prom-k8s-rolebinding.yaml
- hack/olm-registry/olm-artifacts-template.yaml
Since rbac-permissions-operator  will be indirectly deployed, selectorsyncsets need to be generated. This PR:
- Adds a make target for generating selector sync sets
- Adds the needed templates and generation scripts
- Creates `manifests` and the necessary objects to deploy there
WIP, need to add manifests for deployment and for the dedicated-admins group to be deployed.
> Add selectorsyncsets

- Makefile
This PR removes operator-sdk generate from the Makefile since APP-SRE build pipeline doesn't have operator-sdk CLI installed.
> Remove operator-sdk generate from Makefile

- cmd/manager/main.go
- go.mod
Currently, the localmetrics service monitor is not being created when the operator starts. 
```
{"level":"info","ts":1575308345.2894447,"logger":"userMetrics","msg":"Error creating Service Monitor","Error":"no kind is registered for the type v1.ServiceMonitor in scheme \"pkg/runtime/scheme.go:101\""}
{"level":"error","ts":1575308345.28946,"logger":"cmd","msg":"Failed to configure OSD metrics","error":"no kind is registered for the type v1.ServiceMonitor in scheme \"pkg/runtime/scheme.go:101\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tsrc/github.com/openshift/rbac-permissions-operator/cmd/manager/main.go:135\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"} …
```
> Register prometheus operator scheme for ServiceMonitor creation

- pkg/controller/namespace/namespace_controller.go
Bug discovered that the operator is granting permisisons to dedicated-admin SA only and not to the dedicated-admins group (or vice versa). This bug is tracked on OSD-2572
How these changes fix this issue:
line #134 - `continue` instead of `return reconcile.Result{}, nil` because we do not want to exit reconcile 
loop if rolebinding already exists, should just move on to next iteration
line #151 - reconcile loop exits while we are still in the inner for loop, this prevents other rolebindings 
from being created
line #159 - reconcile loop exits after one permission, this prevents other permissions from being loop 
through, thus prevents rolebindings from being created.
sample logs where line 151 is getting hit and reconcile exits when it should not be …
> Fix rolebindings creation on customer namespaces

- hack/olm-registry/olm-artifacts-template.yaml
Currently the cluster-monitoring label is in the wrong place. This PR fixes that issue.
> Move cluster-monitoring label inside metadata

- cmd/manager/main.go
Metrics for operator not exposed as prometheus is reading a different path
> Fix metrics path

- go.mod
I must have run a local build which changed go.mod in https://github.com/openshift/rbac-permissions-operator/pull/65.  This PR removes that change.
> Fix change that snuck into go.mod

- go.mod
- go.sum
Fixes bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
Ref: https://github.com/openshift/cloud-ingress-operator/pull/95
> Fix bitbucket dep

- go.mod
The Dockerfile (even before boilerplate) and prow configuration were both using go 1.13 for builds. For reasons unknown, go.mod claimed 1.14. Things build the same when that line is synced with the rest; so do that.
Forensics: This was switched from 1.13 to 1.14 via commit fbb7d61 as part of operator-sdk upgrade in PR #71. Suspiciously, that's the commit that went from osdk 0.13 to 0.14. Overenthusiastic search/replace? (FWIW, none of the other osdk upgrades I've seen/done have had/needed this switch.)
> Use go 1.13 in go.mod (to match docker build)

- deploy/crds/managed.openshift.io_subjectpermissions_crd.yaml
- pkg/apis/managed/v1alpha1/subjectpermission_types.go
- pkg/apis/managed/v1alpha1/zz_generated.openapi.go
The `State` field in the status is not really used in the controller and is never set. Due to how the API validation is done in Kubernetes an empty string is set to null and this is not allowed according to the CRD. This causes some CSV upgrades to fail in newer versions of openshift.
> Made the state field optional in status

- Makefile
- README.md
To improve the local development process, I have added new targets to the Makefile in order to prepare (`predeploy`) the operator for deployment and also run the operator locally(`deploy-local`).
PTAL
> Add new targets to Makefile to test locally

- build/Dockerfile
Update the build base image to ubi-micro to reduce the future security maintenance overhead
> [OSD-10502] update the base image to ubi-micro

- controllers/namespace/namespace_controller.go
- controllers/subjectpermission/subjectpermission_controller.go
- pkg/controllerutils/controllerutil.go
_(bug)_
Added logic to eliminate terminating and non existing namespaces so that the controller will not try to create resources in these namespaces.
_Fixes #_ [OSD-12502](https://issues.redhat.com/browse/OSD-12502)
> [OSD-12502] handle known error

- README.md
- api/v1alpha1/subjectpermission_types.go
- deploy/crds/managed.openshift.io_subjectpermissions.yaml
- pkg/metrics/metrics.go
- pkg/utility/subjectpermissions_test.go
_(refactor)_
Based on [OSD-2358](https://issues.redhat.com/browse/OSD-2358), this PR removes the allowFirst field from subjectPermission types and CRD because the AllowFirst field is no longer needed/being used
_Fixes #_ [OSD-2358](https://issues.redhat.com/browse/OSD-2358)
> [OSD-2358] Removing allowFirst field

- api/v1alpha1/subjectpermission_types.go
- api/v1alpha1/zz_generated.openapi.go
- controllers/namespace/namespace_controller.go
- controllers/subjectpermission/subjectpermission_controller.go
- deploy/crds/managed.openshift.io_subjectpermissions.yaml
- pkg/const/test/test.go
- pkg/controllerutils/controllerutil.go
- pkg/controllerutils/controllerutil_test.go
feature
Adds support for `subjectNamespace` so SA could be used in a SubjectPermission.
https://issues.redhat.com/browse/OSD-18000
Can use kind Group with name "system:serviceaccounts:<namespace>:<serviceAccountName>" but it's not intuitive.
> Add support for subjectNamespace

- hack/olm-registry/olm-artifacts-template.yaml
/cleanup
the `CatalogSource` spec does not define `affinity` and `tolerations`
fields, those are set in the `grpcPodConfig` which already exists in the
file.
```
2023-12-18T08:03:59Z	INFO	controllers.ObjectSet	API status error with empty reason string	{"ObjectSet": "/managed-openshift-release-bundle-5f548cb8bb", "err": {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"failed to create typed patch object (openshift-rbac-permissions/rbac-permissions-operator-registry; operators.coreos.com/v1alpha1, Kind=CatalogSource): .spec.tolerations: field not declared in schema","code":500}}
```
https://docs.openshift.com/container-platform/4.14/rest_api/operatorhub_apis/catalogsource-operators-coreos-com-v1alpha1.html …
> SDCICD-1178: remove fields not declared in schema

- build/Dockerfile
- build/Dockerfile.olm-registry
- go.mod
- go.sum
- osde2e/rbac_permissions_operator_tests.go
completed todo item for subjectpermissions in e2e test, Removed hardcoded crb name check
_(bug/feature/cleanup/documentation/test/refactor)_
test
1. Removed hardcoded clusterrolebinding name check. This name prefix has changes starting >4.15
2. Adds incomplete todo item for subjectpermissions check 
[SDCICD-1183](https://issues.redhat.com//browse/SDCICD-1183)
_Fixes #_
> SDCICD-1183 e2e test updates

- controllers/namespace/namespace_controller.go
- controllers/subjectpermission/subjectpermission_controller.go
- main.go
- pkg/metrics/metrics.go
bug
This PR fixes the lint issues found in https://github.com/openshift/rbac-permissions-operator/pull/200
We would like to fix the lint issue first then perform a clean boilerplate update.
```
GOOS=linux GOARCH=amd64 CGO_ENABLED=1 GOFLAGS="-tags=fips_enabled" GOEXPERIMENT=boringcrypto GOLANGCI_LINT_CACHE=/tmp/golangci-cache golangci-lint run -c boilerplate/openshift/golang-osd-operator/golangci.yml ./...
../../../controllers/namespace/namespace_controller.go:58:11: QF1008: could remove embedded field "Client" from selector (staticcheck)
err := r.Client.Get(context.TODO(), request.NamespacedName, instance)
^
../../../controllers/namespace/namespace_controller.go:71:10: QF1008: could remove embedded field "Client" from selector (staticcheck)
err = r.Client.List(context.TODO(), …
```
> Fix lint issues
