openshift/rbac-permissions-operator

deploy/crds/managed_v1alpha1_grouppermission_crd.yaml
pkg/apis/managed/v1alpha1/zz_generated.openapi.go

grouppermission_crd.yaml is now updated

generate openapi to update yaml file

---

pkg/apis/managed/v1alpha1/grouppermission_types.go
pkg/controller/add_grouppermission.go
pkg/controller/grouppermission/grouppermission_controller.go
pkg/dedicatedadmin/dedicatedadmin.go
pkg/dedicatedadmin/dedicatedadmin_test.go
pkg/dedicatedadmin/project/resources.go
pkg/utility/grouppermissions.go
pkg/utility/grouppermissions_test.go
pkg/utility/namespaces.go
pkg/utility/namespaces_test.go

From Naveen. 
Not sure if all files in here are needed

added template for controller and needed functions for dedicated admins

---

Makefile
cmd/manager/main.go
go.mod
pkg/apis/addtoscheme_managed_v1alpha1.go
pkg/apis/managed/v1alpha1/zz_generated.openapi.go
pkg/controller/add_grouppermission.go
pkg/controller/grouppermission/grouppermission_controller.go
pkg/utility/grouppermissions.go
pkg/utility/grouppermissions_test.go
project.mk
standard.mk

I didn't catch these paths being generated incorrectly before. Make was also missing our extra function files.

Fix paths to point to openshift repo, make functions

---

pkg/controller/grouppermission/grouppermission_controller.go

Bug: Comparing two []string and output difference onto an array. Nested for loop did not achieve that

fix populateClusterRoleBindingNames bug

---

deploy/namespace.yaml

Name attribute is in the wrong place. Fixing.

Correct namespace defintion

---

deploy/cluster_role.yaml
deploy/cluster_role_binding.yaml
deploy/crds/managed_v1alpha1_subjectpermission_cr.yaml
deploy/crds/managed_v1alpha1_subjectpermission_crd.yaml
deploy/operator.yaml
deploy/service_account.yaml
pkg/apis/managed/v1alpha1/subjectpermission_types.go
pkg/controller/namespace/namespace_controller.go
pkg/controller/subjectpermission/subjectpermission_controller.go
pkg/controller/subjectpermission/subjectpermission_controller_test.go
pkg/controller/utils/controllerutil.go
pkg/localmetrics/localmetrics.go

- changed role and role binding from deploy to cluster role and cluster role binding
- added new CRs for testing
- fix deploy files 
- fix bug in subjectpermission controller
- fix bug in namespace controller
- fix util package

Multiple fixes and test files

---

pkg/controller/subjectpermission/subjectpermission_controller.go

Fix the logic of how we create ClusterRoleBinding. 
1) Loop through every ClusterPermission
2) Create a new ClusterRoleBinding
3) Check if ClusterRoleBinding already exists on cluster
4) Update the condition if all ClusterRoleBindings were added successfully

Remove split of clusterRoleName and SubjectName

---

config/templates/rbac-permissions-operator-csv-template.yaml
hack/app_sre_build_deploy.sh
hack/app_sre_create_image_catalog.sh
hack/app_sre_pr_check.sh
hack/generate-operator-bundle.py
hack/olm-registry/olm-artifacts-template.yaml
hack/validate_yaml.py

- Change variable names to reflect rbac-permissions-operator
- Add selectorSyncSet for olm artifacts template

Add and edit hack folder

---

deploy/operator.yaml

Replace image tag to correct quay link

Replace quay image tag for operator.yaml

---

hack/generate-operator-bundle.py

Fix generate operator bundle to match other operators

Fix generate operator bundle script

---

deploy/cluster_role.yaml
deploy/cluster_role_binding.yaml

Change the ClusterRole rbac-permissions-operator to rbac-permissions-operator-cluster-admin and replicate cluster-admin permissions in it.

Give rbac clusterrole cluster-admin access

---

OWNERS

Add Chris as a reviewer in OWNERS file

Add Chris as reviewer

---

deploy/operator.yaml
hack/olm-registry/olm-artifacts-template.yaml

move workloads to infra nodes

---

hack/olm-registry/olm-artifacts-template.yaml

https://issues.redhat.com/browse/OSD-3163

Use 'Sync' instead of 'sync' for resourceApplyMode

---

build/Dockerfile
go.mod
pkg/dedicatedadmin/dedicatedadmin.go
pkg/dedicatedadmin/dedicatedadmin_test.go
standard.mk
vendor/github.com/openshift/dedicated-admin-operator/config/config.go

https://docs.google.com/presentation/d/1fJCa1DBbNBwurdpCad_VAtYIJ33UEUzkoJVm6XXF2Ro/edit#slide=id.p
- Replace use of "blacklist" with "denylist".
- Remove unused function in dedicatedadmin.go that had reference to ^.
- Updated make stuff to support CONTAINER_ENGINE env var (I build w/ podman).
- Fixed Dockerfile to use path `/workdir` for builds.

Replace use of blacklist with denylist.

---

build/Dockerfile

related to https://github.com/openshift/release/pull/9906

Update to ubi8/go1.13

---

hack/app_sre_create_image_catalog.sh

Fixing Catalog img building script to reference new app-interface repo
OSD-4790

OSD-4790 - Fix Catalog Img build script

---

main.go

Bug
Fixes registration of the rbac-permission-operator types

Fix registration of operator API types

---

docs/testing.md

_(documentation)_
Update the file path to match the operator-sdk structure
_Fixes #OSD-12460_

update the doc to match the new directory structure

---

OWNERS

cleanup
Update OWNERS to add Pratik

Add Pratik to Owners file

---

osde2e/rbac_permissions_operator_tests.go

_(bug/feature/cleanup/documentation/test/refactor)_
test e2e
allows for 120 seconds to check if subjectpermissions successfully applies rolebindings  in a newly created namespace
_Fixes #_

adding  delay in subjectpermission chcks to allow  applying roles

---

build/Dockerfile
build/Dockerfile.olm-registry
go.sum
osde2e/rbac_permissions_operator_tests.go

_(bug/feature/cleanup/documentation/test/refactor)_
Fix
adds missing import for metav1
`00:03:08 30.42 osde2e/rbac_permissions_operator_tests.go:83:50: undefined: metav1`
_Fixes #_

fixing dependency error in build

---

OWNERS
build/Dockerfile
build/Dockerfile.olm-registry

remove Wenqi from the owner as he moved to LP-SRE

remove Wenqi from the owner

---

.github/renovate.json
.tekton/rbac-permissions-operator-pull-request.yaml
.tekton/rbac-permissions-operator-push.yaml

_(bug/feature/cleanup/documentation/test/refactor)_
Feature
updating the on-cel-expression and renovate changes to Konflux Build
https://issues.redhat.com/browse/OSD-30871
_Fixes #_

Adding On-cel and renovate changes
